#!/usr/bin/env bash
set -euo pipefail

# agent-init.sh — one-shot agent repo orientation
# Usage: agent-init.sh <repo-path> [task]
# Output: <repo-path>/VOCAB_PLAN.md  (agent-readable markdown plan)

REPO="${1:-.}"
TASK="${2:-}"
CACHE_DIR="${REPO}/.quale-cache"
PLAN_FILE="${REPO}/VOCAB_PLAN.md"

mkdir -p "$CACHE_DIR"

# agent-bootstrap — working-tree scan only, fast
if [ -n "$TASK" ]; then
    python3 -m quale.cli agent-bootstrap "$REPO" --task "$TASK" --format json \
        > "$CACHE_DIR/bootstrap.json" 2>/dev/null || true
    python3 -m quale.cli agent-bootstrap "$REPO" --task "$TASK" --summary \
        2>/dev/null | head -30 > "$CACHE_DIR/bootstrap_summary.txt" || true
else
    python3 -m quale.cli agent-bootstrap "$REPO" --format json \
        > "$CACHE_DIR/bootstrap.json" 2>/dev/null || true
    python3 -m quale.cli agent-bootstrap "$REPO" --summary \
        2>/dev/null | head -30 > "$CACHE_DIR/bootstrap_summary.txt" || true
fi

# ci-report on recent changes (up to 5 commits back, fast path)
python3 -m quale.cli ci-report HEAD~5 HEAD --path "$REPO" --format json \
    > "$CACHE_DIR/ci.json" 2>/dev/null || true
python3 -m quale.cli ci-report HEAD~5 HEAD --path "$REPO" --summary \
    2>/dev/null | head -20 > "$CACHE_DIR/ci_summary.txt" || true

# detect environment for the agent
LANG_COUNT=$(python3 -c "
import json,sys
try:
    d=json.load(open('$CACHE_DIR/bootstrap.json'))
    files=d.get('related_files_for_task') or d.get('recommended_next_reads') or []
    langs={}
    for f in d.get('module_boundaries',[]):
        for l in f.get('languages',[]):
            langs[l]=langs.get(l,0)+1
    print(len(langs))
except: print(0)
" 2>/dev/null || echo 0)

# generate plan
cat > "$PLAN_FILE" << PLANHEADER
# Repo Plan

Generated by \`quale agent-init.sh\`.

PLANHEADER

if [ -s "$CACHE_DIR/bootstrap_summary.txt" ]; then
    echo "## Orientation" >> "$PLAN_FILE"
    cat "$CACHE_DIR/bootstrap_summary.txt" >> "$PLAN_FILE"
    echo "" >> "$PLAN_FILE"
fi

if [ -s "$CACHE_DIR/ci_summary.txt" ]; then
    echo "## Recent Changes" >> "$PLAN_FILE"
    cat "$CACHE_DIR/ci_summary.txt" >> "$PLAN_FILE"
    echo "" >> "$PLAN_FILE"
fi

if [ -n "$TASK" ]; then
    echo "## Task: $TASK" >> "$PLAN_FILE"
fi

echo "## Key Paths" >> "$PLAN_FILE"
echo "- Cached JSON: \`.quale-cache/bootstrap.json\`" >> "$PLAN_FILE"
echo "- Cached CI: \`.quale-cache/ci.json\`" >> "$PLAN_FILE"

# detect active branch
BRANCH=$(cd "$REPO" && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
echo "- Branch: \`$BRANCH\`" >> "$PLAN_FILE"

echo "" >&2 "Plan written to $PLAN_FILE"
